name: fastapi-mysql

services:   
  db-mysql:  # Solo el servicio de la base de datos MySQL, sin la aplicaci√≥n FastAPI
    image: mysql 
    container_name: db-mysql   
    environment:  
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: peliculasdb
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: 1234
    ports:  
      - "3307:3306"  
