name: fastapi-peliculas

services: 
  fastapi-app:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    container_name: fastapi-app-peliculas
    restart: always  
    ports:  
      - "8000:8000"  
    depends_on:  
      - fastapi-db  
  fastapi-db:  
    image: mysql 
    container_name: fastapi-db-peliculas
    environment:  
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: peliculasdb
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: 1234
    ports:  
      - "3307:3306"  
  