name: fastapi-peliculas-postgres
# La app es independiente de la base de datos. 
# La configuracion se realiza mediante variables de entorno
# Esto permite cambiar de MySQL a Postgres sin cambiar la app 
services:
  fastapi-app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-peliculas
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    environment:
      DB_URL: postgresql+psycopg2://quevedo:1234@postgres-db:5432/peliculasdb

  postgres-db:
    image: postgres:16
    container_name: postgres-db-peliculas
    environment:
      POSTGRES_DB: peliculasdb
      POSTGRES_USER: quevedo
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
