name: fastapi-peliculas-postgres
services:
  fastapi-app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-peliculas
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16
    container_name: postgres-db-peliculas
    environment:
      POSTGRES_DB: peliculasdb
      POSTGRES_USER: quevedo
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
